#!/usr/bin/perl
# ---   *   ---   *   ---
# deps

use v5.36.0;
use strict;
use warnings;

use Readonly;

# ---   *   ---   *   ---
# ROM

  Readonly my $ROOT=>qr{^lycon:};

# ---   *   ---   *   ---
# GBL

my $Font  = "lycon";
my $Level = 0;
my $Base  = 24;
my $Ftog  = 0;

my @Scr   = ();
scrget();

# ---   *   ---   *   ---
# recalc screen size

sub scrget {
  @Scr=split m[\s+],`stty size`;

};

# ---   *   ---   *   ---
# nit

sub on_start {

  my ($self) = @_;


  # this is hacky, but there doesn't
  # seem to be an event after
  # window creation
  $self->{timer}=urxvt::timer->new;
  $self->{timer}->after(0.1)->cb(
    sub {fullscreen($self)}

  );

  return;
}

# ---   *   ---   *   ---
# crux

sub on_user_command {


  state $tab={

    fullscreen => \&fullscreen,

    zoomin     => \&zoom,
    zoomout    => \&zoom,

    pageup     => \&scroll,
    pagedown   => \&scroll,

  };

  my ($self,$cmd) = @_;
  $cmd=~ s[$ROOT][];

  my $fn=$tab->{$cmd};
  $fn->($self,$cmd) if defined $fn;


  return;


};

# ---   *   ---   *   ---
# selfex

sub fullscreen($self,@slurp) {


  if(exists $self->{timer}) {

    my $wid = $self->parent;
    my $err = `wmctrl -i -r $wid -b add,fullscreen`;

    warn "Error maximizing: $err\n" unless $? == 0;
    $self->{timer}->stop;

    delete $self->{timer};

    $Ftog |= 1;


  } else {
    `wmctrl -r :ACTIVE: -b toggle,fullscreen`;
    $Ftog ^= 1;

  };


  return;

};

# ---   *   ---   *   ---
# make font bigger or smaller

sub zoom($self,$cmd) {

  if ($cmd eq 'zoomin') {
    $Level += 4*($Level < 64);

  } elsif ($cmd eq 'zoomout') {
    $Level -= 4*($Level > -23);

  };

  my $size = $Base+$Level;
  my $aa   = ($size >= $Base)
    ? 'false'
    : 'true'
    ;

  my $paste=

    "xft:${Font}:"

  . "pixelsize=${size}:"
  . "antialias=$aa:"
  . "autohint=$aa"
  . "\007"

  ;

  $self->cmd_parse(

    "\033]50;$paste"
  . "\033]51;$paste"

  . "\033[8;0;0t"

  );

  my $wid = $self->parent;
#  my $err = `wmctrl -i -r $wid -e 1,0,0`;


  if($Ftog) {
    fullscreen($self);
    fullscreen($self);

  };


  scrget();
  return;

};

# ---   *   ---   *   ---
# go up or down a page

sub scroll($self,$cmd) {

  my $me = "\033]720";

  if($cmd eq 'pageup') {
    $me="\033]720";


  } elsif($cmd eq 'pagedown') {
    $me="\033]721";

  };

  $self->cmd_parse("$me;$Scr[0]\007");


  return;

};

# ---   *   ---   *   ---
